version: '3.0'

services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sales
      POSTGRES_USER: user
    ports:
      - 5432:5432
    volumes:
    - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    container_name: postgres

  tomcat:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    container_name: tomcat

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    container_name: adminer